on: [push]
name: Publish app
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: git clone https://github.com/emscripten-core/emsdk.git
      - run: cd emsdk && ./emsdk install latest && ./emsdk activate latest && source ./emsdk_env.sh
      - run: mkdir app/build && ./emsdk/upstream/emscripten/emcc src/*.c -o app/build/index.html -sUSE_SDL=2 -sEXPORTED_RUNTIME_METHODS=ccall,cwrap --shell-file app/template/shell.html
      - uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: app/build
  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - uses: actions/deploy-pages@v4
